# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: fast-api CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test python Code
        run: |
          pip3 install -r requirements.txt
          pip3 install pytest
          cd app/
          pytest

  build-push-container:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          docker build -t jhocan55/fast-api:${GITHUB_SHA} .
          docker tag  jhocan55/fast-api:${GITHUB_SHA} jhocan55/fast-api:latest
          docker images
          docker run -d -p 80:80 --name fastapi jhocan55/fast-api:${GITHUB_SHA}
          sleep 10
          docker login -u "${{ secrets.REGISTRY_USER }}" -p "${{ secrets.REGISTRY_PASSWD }}"
          docker push jhocan55/fast-api:${GITHUB_SHA}
          sleep 1
          
          docker push jhocan55/fast-api:latest

  deploy:
    needs: build-push-container
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTNAME  }}
          username: ${{ secrets.USER_NAME  }}
          key: ${{ secrets.AWS_PRIVATE_KEY  }}
          port: 22 
          script: |
            sudo docker rm -f fastapi 
            sudo docker rmi jhocan55/fast-api:latest
            sleep 10 
            sudo docker run -d -p 9000:80 --name fastapi jhocan55/fast-api:latest
            sudo docker ps 
            sleep 10 
            curl localhost:9000
            ls 
            sudo docker images
